service: s7-indian-cars

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  timeout: 60
  iamRoleStatements:
     - Effect: "Allow"
       Action: 
          - "s3:getObject"
          - "s3:PutObject"
          - "s3:PutObjectAcl"
          - "s3:GetObjectAcl"
       Resource: "arn:aws:s3:::eva4p2-session1/*"

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy: 
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: "./cache"

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/**

functions:
  get_cars:
    handler: handler.get_cars
    memorySize: 3008
    timeout: 60
    events: 
        - http:
                path: getcars
                method: post
                cors: true

plugins:
  - serverless-python-requirements
